### ISSUE TITLE
Option to exclude metadata from license list output

### ISSUE THREAD

**Issue by olee** [mhassan1/yarn-plugin-licenses#10]
It would be nice to get an option to exclude metadata like url, vendorUrl and vendorName from the console output as this makes the list quite huge and is not necessary usually.
I would even say that it should be rather excluded by default and only added when an option is enabled.

**Comment by mhassan1** [comment]
Check out PR https://github.com/mhassan1/yarn-plugin-licenses/pull/11. I'd rather not make it default because it would be a breaking change and because this library is meant as a (mostly) drop-in replacement for Classic Yarn `licenses`.
