### ISSUE TITLE
Feature request: --production browser licenses

### ISSUE THREAD

**Issue by raDiesle** [mhassan1/yarn-plugin-licenses#22]
would be nice to have included only browser licenses like its done by 
https://www.npmjs.com/package/@cyclonedx/bom

Actually cyclone also has no specific flag - seems like --production works different compared to the yarn-plugin-licenses.

As per law, browser shipped dependencies must be generated.

**Comment by mhassan1** [comment]
Thanks for the feature request!

What are browser licenses? Do you have an example of a `package.json` and what you would expect for the output of `yarn licenses`?

**Comment by raDiesle** [comment]
My setup is a web application based on Create-React-App.
By law, you must provide licenses for libraries used in the browser, not the ones used in the server or for the build.

So this is what i mean by "browser licenses".

I am not sure how exactly they do it but cyclonedx ( but they dont have support for pnp, yet) gives me the licenses I need, in comparison yarn-plugin-licenses gives me too many licenses, maybe devDependencies as well.

**Comment by mhassan1** [comment]
How is the desired result different from `yarn licenses --production`?

**Comment by mhassan1** [comment]
`yarn licenses generate-disclaimer --production` is already supported. Please try it.

**Comment by raDiesle** [comment]
your right I did diff.... weird. wrong statement from me. I will then compare and figure out
