### ISSUE TITLE
Bug: no such file to open --recursive

### ISSUE THREAD

**Issue by raDiesle** [mhassan1/yarn-plugin-licenses#23]
Got this ony my machine with yarn3 and pnp.

yarn licenses list --recursive
Internal Error: ENOENT: no such file or directory, open '/home/react-ui/.yarn/unplugged/fsevents-patch-fcdf30aaca/node_modules/fsevents/package.json'
Error: ENOENT: no such file or directory, open '/home/react-ui/.yarn/unplugged/fsevents-patch-fcdf30aaca/node_modules/fsevents/package.json'

**Comment by mhassan1** [comment]
Can you please provide steps to reproduce?

**Comment by raDiesle** [comment]
Let me ask like this: does yarn-plugin licenses support yarn berry pnp strict mode?

I can try to reproduce, but I am assume its not supported pnp?

**Comment by mhassan1** [comment]
Yes, it supports PnP; see integration tests [here](https://github.com/mhassan1/yarn-plugin-licenses/tree/main/src/__tests__/integration/fixtures).

**Comment by auberryberry** [comment]
I'm seeing similar errors ironically for the same fsevents library, maybe it just needs error handling around package.json not existing?

**Comment by mhassan1** [comment]
Please provide steps to reproduce, i.e. `yarn -v`, sample `package.json`, version of this plugin, OS, etc. I can't reproduce with `yarn@3.2.3` and `v0.8.1` of this plugin.

**Comment by mhassan1** [comment]
@raDiesle @auberryberry Are you still hitting this issue? I'd like to help, but I'll need some reproduction steps.
