### ISSUE TITLE
Yarn 2 commit for Clipanion breaks the plugin

### ISSUE THREAD

**Issue by Nikki1993** [mhassan1/yarn-plugin-licenses#4]
Apologies for lack of error message as I've already downgraded yarn but the latest yarn 2 from master aka

`yarn set version from sources`

breaks all plugins due to this commit https://github.com/yarnpkg/berry/commit/b433198b9d2fb6ab81a9e23e8f00021bc5bafb4d

The plugin will have to be changed in order to work with latest master branch.

**Comment by mhassan1** [comment]
I've just gotten word that the next yarn release will be v3, so master contains breaking changes. You'll need to stick with yarn 2.4.0 for this plugin to work. Once yarn 3 comes out, I'll create a breaking release of this plugin. Does that work for you?

**Comment by Nikki1993** [comment]
It's perfectly fine, thank you very much for the plugin and the work you did on it! I just took this opportunity to throw a heads-up.
