### ISSUE TITLE
Is this supposed to find all installed licenses?

### ISSUE THREAD

**Issue by prewk** [mhassan1/yarn-plugin-licenses#58]
..because in a zero-install yarn PNP repo it doesn't, for me. It finds a handful, but the majority has nothing.

For instance:

We have a transient dep `react-colorful` because of storybook. It's in the cache directory as `.yarn/cache/react-colorful-npm-5.6.1-ba0c706357-48eb73cf71.zip`
If I unzip it and check out `package.json` it's correctly specified as MIT. Yet - this plugin can't find a license for this package.

Am I misunderstanding something?
(Thanks for your work!)

**Comment by mhassan1** [comment]
It should list all licenses. Are you passing the `-R` flag?

**Comment by prewk** [comment]
Ah, didn't see that flag! Should've went with `--help` first. Thanks!
