### ISSUE TITLE
Better license finding

### ISSUE THREAD

**Issue by brandon-leapyear** [mhassan1/yarn-plugin-licenses#7]
As an example, NPM shows [passport-local](https://www.npmjs.com/package/passport-local) as having no license, but if you go to `package.json`, it has both `"license": "MIT"` and `"licenses": [{"type":"MIT", "url": "..."}]`. It would be great if this plugin bypassed what NPM says and look directly at the dep's package.json

**Comment by mhassan1** [comment]
It looks like tag `v1.0.0` of that library doesn't have `license` and only has `licenses` in its `package.json`: https://github.com/jaredhanson/passport-local/blob/v1.0.0/package.json#L26-L31

It seems like the `license` field was added after the 1.0.0 release but they never did another release...

This library checks the dependency's `package.json` here: https://github.com/mhassan1/yarn-plugin-licenses/blob/5be13c2e63e8afe428e832e2bcd08d983a88cce4/src/utils.ts#L47-L52

**Comment by brandon-leapyear** [comment]
ah ok. I thought I saw a lot more "MISSING" licenses, but I guess not. Thanks!

**Comment by brandon-leapyear** [comment]
Here's an example: https://github.com/mscdex/busboy/blob/master/package.json

Can you also look in `licenses`?

**Comment by brandon-leapyear** [comment]
Also, this package has `license` set, but I'm seeing `UNKNOWN`: https://github.com/Raynos/min-document/blob/1b5402dcd5df3bf2575e71d463baa44dc2c05571/package.json#L28

**Comment by mhassan1** [comment]
This will be addressed by #9

**Comment by brandon-leapyear** [comment]
Thanks!
